---
title: "ST561: Homework 1"
author: 
    - "Brian Cervantes Alvarez"
date: "10-09-2023"
format: PrettyPDF-pdf
execute: 
  warning: false
  message: false
editor: visual
---

# Problems

## Question 1

1.  Textbook, Page 37, Exercise 1.1

    (a) 
    (b)
    (c)
    (d)

{{< pagebreak >}}

## Question 2

2.  Suppose that you own 6 different Spanish textbooks, 4 different History textbooks, 4 different Geology textbooks, and 5 different English textbooks. You have reserved a shelf on a bookcase on which you place all these textbooks. How many different ways are there to place all 19 textbooks on the shelf so that all the textbooks in a given subject are grouped together?

{{< pagebreak >}}

## Question 3

3.  Four cards are drawn from a deck of 52 ordinary playing cards, without replacement.
    (a) What is the probability that all 4 cards are aces?
    (b) What is the probability of drawing, in order, the aces of clubs, diamonds, hearts, and spades?
    (c) Answer (a) and (b) above if each card is replaced (and the deck shuffled) after it is drawn.

{{< pagebreak >}}

## Question 4

4.  Find the union $A_1 \cup A_2$ and the intersection $A_1 \cap A_2$ of the two sets $A_1$ and $A_2$ where

    (a) $A_1 = \{x: 0 < x < 1\}$, $A_2 = \{x: 1 \leq x < 3\}$;
    (b) $A_1 = \{(x, y): 0 \leq x < 3, 0 < y \leq 3\}$, $A_2 = \{(x, y): 1 < x \leq 4, 1 \leq y < 4\}$; (Draw a picture to show the set.)
    (c) $A_1 = \{(x, y): x + y \leq 1, x \geq 0, y \geq 0\}$, $A_2 = \{(x, y): x^2 + y^2 \leq \frac{1}{2}, x \geq 0, y \geq 0\}$.

    You are not required to show your work for this problem.

{{< pagebreak >}}

## Question 5

5.  (Urn Model) r different balls $B_1, \ldots, B_r$ are to be randomly put into n different urns $U_1, \ldots, U_n$ ($r \leq n$). What is the probability of the following events?
    (a) Urns $U_1, \ldots, U_r$ each contains exactly one ball;
    (b) No urn contains more than one ball;
    (c) Urn $U_1$ contains exactly $m$ balls ($m \leq r$).

{{< pagebreak >}}

## Question 6

6.  Suppose $n > 0$, $0 \leq k \leq n$. Show that
    (a) ${n \choose k} = \frac{n!}{k!(n-k)!}$
    (b) ${n \choose 0} = {n \choose n} = 1$
    (c) ${n \choose 1} = n$
    (d) If $k > 1$, ${n \choose k} = {n-1 \choose k-1} + {n-1 \choose k}$.

Can you give intuitive explanations for the results above? (You do not have to turn in your explanations.)

{{< pagebreak >}}

## Question 7

7.  Consider the experiment of dealing a five-card poker hand at random from a deck of 52 ordinary playing cards. Let A be the event that you obtain a full house (3 cards of one rank and 2 cards of a second rank, e.g., 3 kings and 2 eights). Let B be the event that you obtain two pairs (2 cards of one rank, 2 cards of a second rank, and a 5th card of a third rank, e.g., 2 tens, 2 threes, and the Jack of diamonds). One of the following two probabilities is correct, and the other probability is incorrect.

    (a) Determine which probability is correct.
    (b) Correct the incorrect probability.
    (c) Explain clearly how the correct probability is obtained and why the incorrect probability is wrongly calculated.
